### ISSUE TITLE
[文章]如何快速向RT-Thread提一个PR

### ISSUE THREAD

**Issue by dejavudwh** [dejavudwh/about-rt-thread#14]
构思：
- PR方法（Git操作）
- 代码功能修改
  - 代码定位
  - 代码阅读
  - 功能增加
- PR心得

**Comment by dejavudwh** [comment]
PR：https://github.com/RT-Thread/rt-thread/pull/7499

**Comment by supperthomas** [comment]
结束的任务可以close
